global:
  commonAnnotations: {}
  commonLabels: {}

  # For adguard dns so it doesnt try to take 200Gi of storage
  fallbackDefaults:
    pvcSize: 2Gi
    vctSize: 2Gi

enabled: true

networkPolicy:
  enabled: false
  ingress:
    traefikNamespace: traefik
    traefikPodSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik
    
dashboard:
  enabled: false
  ingressUrl: "adguardhome.example.com"
  middlewares:
    - name: traefik-default-chain 
      namespace: traefik
  entrypoint: websecure
  cert:
    externalSecret:
      enabled: false
      secretName: "example-com-tls"
      secretStore: "certs-vault"
      secretStoreType: "ClusterSecretStore"
    reflectedSecret:
      enabled: true
      originNamespace: "external-secrets"
      originSecretName: "example-com-tls"

# https://github.com/trueforge-org/truecharts/blob/master/charts/stable/adguard-home/values.yaml
adguard-home: 
  enabled: true 
  service: 
    main: 
      # Loadbalancer is usefull during setup or
      # or if you want to expose to external services
      # type: LoadBalancer
      type: ClusterIP
      loadBalancerIP: ""
      # port: 8080
      protocol: http

  # Can be overruled per container
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 75m
      memory: 200Mi
