global:
  commonLabels: {}
  commonAnnotations: {}

# Enable the resources in this chart
enabled: true

# -- Credentials
secretName: adguardhome-sync-secret
externalSecret:
  enabled: true
  secretName: adguardhome-sync-secret
  storeName: kubernetes
  storeType: SecretStore
  properties:
    ORIGIN_USERNAME: ""
    ORIGIN_PASSWORD: ""
    REPLICA_USERNAME: ""
    REPLICA_PASSWORD: ""

adguardhome-sync:
  enabled: true

  TZ: "UTC"

  # -- Resources
  # Can be overruled per container
  resources:
    limits:
      cpu: 1000m
      memory: 1500Mi
    requests:
      cpu: 100m
      memory: 250Mi

  # -- (docs/service/README.md)
  service: 
    main: 
      type: LoadBalancer
      loadBalancerIP: ""
      ports: 
        main: 
          port: 8080
          targetPort: 8080
          protocol: http

  credentials: {}
  # mys3:
  #   type: s3
  #   url: ""
  #   path: ""
  #   bucket: ""
  #   accessKey: ""
  #   secretKey: ""
  #   ## Is used in cases where things are encrypted by a backup utility
  #   encrKey: ""

  secret: {}

  workload:
    main:
      podSpec:
        containers:
          main:
            args:
              - run
            env:
              CRON: "*/10 * * * *"
              FEATURES_CLIENT_SETTINGS: true
              FEATURES_DHCP_SERVER_CONFIG: true
              FEATURES_DHCP_STATIC_LEASES: true
              FEATURES_DNS_ACCESS_LISTS: true
              FEATURES_DNS_REWRITES: true
              FEATURES_DNS_SERVER_CONFIG: true
              FEATURES_FILTERS: true
              FEATURES_GENERAL_SETTINGS: true
              FEATURES_QUERY_LOG_CONFIG: true
              FEATURES_SERVICES: true
              FEATURES_STATS_CONFIG: true
              ORIGIN_URL: https://192.168.1.2:3000
              REPLICA_AUTO_SETUP: false
              REPLICA_INTERFACE_NAME: ""
              REPLICA_URL: http://192.168.1.3
              RUN_ON_START: true
              # The following are set using a secret
              # ORIGIN_PASSWORD: password
              # ORIGIN_USERNAME: username
              # REPLICA_PASSWORD: password
              # REPLICA_USERNAME: username
            envFrom:
              - secretRef:
                  name: {{ .Values.credentials.secretName | quote }}