apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: vault-system
    server: https://kubernetes.default.svc
  project: infrastructure
  sources:
    - repoURL: https://example.com/your-repo
      targetRevision: HEAD
      ref: gitopsDir
    - repoURL: https://github.com/Nynra/k3s-charts
      targetRevision: HEAD
      path: charts/development/banzai-vault
      helm:
        valueFiles:
          - $gitopsDir/configs/vault-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
