global:
  commonLabels: {}
  commonAnnotations: {}

# Enable the resources in this chart
enabled: true

# -- Credentials
origin:
  # Needs to match the secret in the workload container below
  secretName: "origin-credentials"
  reflectedSecret:
    enabled: true
    originNamespace: cert-manager
    originSecretName: goosebutnine-nl-tls

replica:
  # Needs to match the secret in the workload container below
  secretName: "replica-credentials"
  reflectedSecret:
    enabled: true
    originNamespace: cert-manager
    originSecretName: goosebutnine-nl-tls

syncConfig:
  autoSetupReplica: false
  syncInterval: "*/5 * * * *"
  features:     
    # DNS
    dnsAccessLists: true
    dnsRewrites: true
    dnsServerConfig: true
    filters: true

    # DHCP
    dhcpServerConfig: false
    dhcpStaticLeases: false
    
    # General
    generalSettings: true
    queryLogConfig: true
    services: true
    statsConfig: true
    clientSettings: false

adguardhome-sync:
  enabled: true

  TZ: "UTC"

  # -- Resources
  # Can be overruled per container
  resources:
    limits:
      cpu: 1000m
      memory: 1500Mi
    requests:
      cpu: 100m
      memory: 250Mi

  workload:
    main:
      podSpec:
        containers:
          main:
            args:
              - run
            env:
              CRON: "*/5 * * * *"
              FEATURES_CLIENT_SETTINGS: "true"
              FEATURES_DHCP_SERVER_CONFIG: "false"
              FEATURES_DHCP_STATIC_LEASES: "false"
              FEATURES_DNS_ACCESS_LISTS: "true"
              FEATURES_DNS_REWRITES: "true"
              FEATURES_DNS_SERVER_CONFIG: "true"
              FEATURES_FILTERS: "true"
              FEATURES_GENERAL_SETTINGS: "true"
              FEATURES_QUERY_LOG_CONFIG: "true"
              FEATURES_SERVICES: "true"
              FEATURES_STATS_CONFIG: "true"
              REPLICA_AUTO_SETUP: "false"
              REPLICA_INTERFACE_NAME: ""
              RUN_ON_START: true
              # The following are set using a secret
              # REPLICA_URL: "{{ .Values.replica.address }}"
              # ORIGIN_PASSWORD: password
              # ORIGIN_USERNAME: username
              # ORIGIN_URL: "{{ .Values.origin.address }}"
              # REPLICA_PASSWORD: password
              # REPLICA_USERNAME: username
            envFrom:
              - secretRef:
                  name: "origin-credentials"
              - secretRef:
                  name: "replica-credentials"