apiVersion: v2
name: openfaas-wrapper
description: A Helm chart that deploys OpenFaaS with ingress.
type: application
version: "0.0.1"
dependencies:
- name: openfaas
  version: "14.2.124"
  repository: https://openfaas.github.io/faas-netes/
  condition: openfaas.enabled